version: '3.7'
services:
  gateway:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./gateway/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - api-login
    networks:
      - app-network

  api-login:
    build:
      context: ./api/api-login
    environment:
      - TZ=Asia/Bangkok
    networks:
      - app-network
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    command: "npm run dev -- --host"
    volumes:
      - ./web/src:/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Bangkok
    networks:
      - app-network

networks:
  app-network:

    