version: '3.7'
services:
  gateway:
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./gateway/conf.d:/etc/nginx/conf.d
    depends_on:
      - web
      - api-login
    networks:
      - app-network

  api-login:
    build:
      context: ./api/api-login
    environment:
      - TZ=Asia/Bangkok
    networks:
      - app-network
  
  web:
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    ports:
      - 5173:5173
    command: "npm run dev -- --host"
    volumes:
      - ./web/src:/app/src
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - TZ=Asia/Bangkok
    networks:
      - app-network
  
  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "P@ssw0rd"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    networks:
      - db-network

  adminer:
    image: adminer
    ports:
      - 8081:8080
    networks:
      - db-network

networks:
  app-network:
  db-network:

    